name: webscrape
channels:
  - conda-forge
dependencies:
        - numpy
        - python
        - ipython
        - wget
        - requests
        - pandas
        - matplotlib
        - wordcloud
        - jupyter
